FROM alpine:latest
MAINTAINER tqhnet
ENV VERSION 1.0

# 为我们的镜像设置必要的环境变量
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GO_ENV=dev

# 在容器根目录 创建一个 apps 目录
WORKDIR /apps

# 拷贝当前目录下 的 可以执行文件
COPY ./.build/app /apps/app

# 设置时区为上海
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

# 设置编码
ENV LANG C.UTF-8

# 暴露端口
EXPOSE 8888

# 运行golang程序的命令
ENTRYPOINT ["/apps/app"]
